# Generated by Django 5.2.7 on 2026-02-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiaries', '0004_alter_beneficiary_address_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='civil_status',
            field=models.CharField(choices=[('single', 'Solteiro(a)'), ('married', 'Casado(a)'), ('divorced', 'Divorciado(a)'), ('separated', 'Separado(a)'), ('widowed', 'Viúvo(a)')], default='single', max_length=30, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='community_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome da comunidade'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='education',
            field=models.CharField(choices=[('no_formal_education', 'Sem instrução formal'), ('basic_literacy', 'Alfabetizado (sem escolarização formal)'), ('elementary_incomplete', 'Ensino Fundamental incompleto'), ('elementary_complete', 'Ensino Fundamental completo'), ('high_school_incomplete', 'Ensino Médio incompleto'), ('high_school_complete', 'Ensino Médio completo'), ('technical', 'Ensino Técnico (nível médio)'), ('undergraduate_incomplete', 'Ensino Superior incompleto'), ('undergraduate_complete', 'Ensino Superior completo'), ('specialization', 'Pós-graduação (Especialização / MBA)'), ('masters', 'Mestrado'), ('doctorate', 'Doutorado'), ('postdoctorate', 'Pós-Doutorado')], default='no_formal_education', max_length=50, verbose_name='Escolaridade'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='emergency_contact',
            field=models.JSONField(blank=True, null=True, verbose_name='Contatos de Emergência'),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='race',
            field=models.CharField(blank=True, choices=[('white', 'Branca'), ('black', 'Preta'), ('brown', 'Parda'), ('asian', 'Amarela'), ('indigenous', 'Indígena')], max_length=20, null=True, verbose_name='Cor/Raça'),
        ),
    ]
